--<ScriptOptions statementTerminator=";"/>

CREATE TABLE EXPFATU (
		NCODIFATU NUMBER(8 , 0) NOT NULL,
		DDATAFATU DATE DEFAULT SYSDATE,
		CNFATFATU VARCHAR2(13),
		CN_LIFATU VARCHAR2(12),
		CNCRTFATU VARCHAR2(15),
		CN_DIFATU VARCHAR2(12),
		NCDFAMOED NUMBER(2 , 0) NOT NULL,
		NCDFRMOED NUMBER(2 , 0) NOT NULL,
		NVLFRFATU NUMBER(15 , 2) NOT NULL,
		NCDIMENTI NUMBER(6 , 0) NOT NULL,
		CPOORFATU VARCHAR2(30) NOT NULL,
		CPODEFATU VARCHAR2(30) NOT NULL,
		DDTIEFATU DATE,
		DDTFEFATU DATE,
		NCDDEENTI NUMBER(6 , 0),
		CSITUFATU CHAR(1) DEFAULT 'A'  NOT NULL,
		NCODIDESP NUMBER(6 , 0),
		DVEDIFATU DATE,
		COBS_FATU VARCHAR2(3500),
		CTPNGFATU CHAR(1) NOT NULL,
		CREFRFATU CHAR(1) NOT NULL,
		NCODICTCV NUMBER(7 , 0),
		NCODIFILI NUMBER(2 , 0) NOT NULL,
		NNUMEFECU NUMBER(2 , 0),
		NNUMEFEPR NUMBER(2 , 0),
		CCOVEFATU VARCHAR2(1),
		CTPTRFATU VARCHAR2(1) DEFAULT 'R'  NOT NULL,
		NCDSGMOED NUMBER(2 , 0),
		NVLSGFATU NUMBER(15 , 2),
		CCCOMFATU VARCHAR2(13)
	);

CREATE INDEX IFK_NCDFRMOED_EXPFATU ON EXPFATU (NCDFRMOED ASC);

CREATE INDEX IFK_NCDFAMOED_EXPFATU ON EXPFATU (NCDFAMOED ASC);

CREATE INDEX IFK_NCODICTCV_EXPFATU ON EXPFATU (NCODICTCV ASC);

CREATE INDEX IFK_NCDDEENTI_EXPFATU ON EXPFATU (NCDDEENTI ASC);

CREATE UNIQUE INDEX PK_EXPFATU ON EXPFATU (NCODIFATU ASC);

CREATE INDEX IFK_NCODIFILI_EXPFATU ON EXPFATU (NCODIFILI ASC);

CREATE INDEX IFK_NCDIMENTI_EXPFATU ON EXPFATU (NCDIMENTI ASC);

CREATE INDEX IFK_NCODIDESP_EXPFATU ON EXPFATU (NCODIDESP ASC);

ALTER TABLE EXPFATU ADD CONSTRAINT PK_EXPFATU PRIMARY KEY (NCODIFATU);

ALTER TABLE EXPFATU ADD CONSTRAINT FK_NCODIFILI_EXPFATU FOREIGN KEY (NCODIFILI)
	REFERENCES CFGFILI (NCODIFILI)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE EXPFATU ADD CONSTRAINT FK_NCDSGMOED_EXPFATU FOREIGN KEY (NCDSGMOED)
	REFERENCES CFGMOED (NCODIMOED)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE EXPFATU ADD CONSTRAINT FK_NCODICTCV_EXPFATU FOREIGN KEY (NCODICTCV)
	REFERENCES CTRCTCV (NCODICTCV)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE EXPFATU ADD CONSTRAINT FK_NCODIDESP_EXPFATU FOREIGN KEY (NCODIDESP)
	REFERENCES EXPDESP (NCODIDESP)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

